---
abstract: 'Experimental Padre plugin written in Perl 6'
author:
  - 'Gabor Szabo <szabgab@gmail.com>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-PSI
no_index:
  directory:
    - inc
    - t
requires:
  Inline::Rakudo: 0.02
  Padre: 0.29
resources:
  bugtracker: http://padre.perlide.org/
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-PSI
version: 0.01
